devices: ["mps:0"]
dtype: "fp32"
output_folder: "../logs"
loader:
  batch_size: 32
dataset:
  name: "MovieLens20M"
  train: "movie"
  test: "val"
  img_folder: "../data/MovieLens20M/posters"
  ann_folder: "../data/MovieLens20M"
model:
  num_genres: 19
opt:
  warmup_epochs: 3
  epochs: 10
  learning_rate: 0.02